Models/DiaryEntries.cs
using System.ComponentModel.DataAnnotations;

namespace ElizabethRobinsonDiaryEntries.Models
{
    public class DiaryEntries
    {
        public int Id { get; set; }
        [Display(Name = "Title")]
        public string EntryName { get; set; }
        [Display(Name = "Entry Date")]
        public DateTime EntryDate { get; set; }
        [Display(Name = "Content")]
        public string EntryContext { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ElizabethRobinsonDiaryEntries.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DiaryEntriesController.cs
using ElizabethRobinsonDiaryEntries.Data;
using ElizabethRobinsonDiaryEntries.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ElizabethRobinsonDiaryEntries.Controllers
{
    public class DiaryEntriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DiaryEntriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DiaryEntries
        public async Task<IActionResult> Index()
        {
            return View(await _context.DiaryEntries.ToListAsync());
        }

        // GET: DiaryEntries/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // PoST: DiaryEntries/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string searchPhrase)
        {
            return View("Index", await _context.DiaryEntries.Where(x => x.EntryContext.Contains(searchPhrase)).ToListAsync());
        }

        // GET: DiaryEntries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DiaryEntries == null)
            {
                return NotFound();
            }

            var diaryEntries = await _context.DiaryEntries
                .FirstOrDefaultAsync(m => m.Id == id);
            if (diaryEntries == null)
            {
                return NotFound();
            }

            return View(diaryEntries);
        }

        // GET: DiaryEntries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DiaryEntries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EntryName,EntryDate,EntryContext")] DiaryEntries diaryEntries)
        {
            if (ModelState.IsValid)
            {
                _context.Add(diaryEntries);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(diaryEntries);
        }

        // GET: DiaryEntries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DiaryEntries == null)
            {
                return NotFound();
            }

            var diaryEntries = await _context.DiaryEntries.FindAsync(id);
            if (diaryEntries == null)
            {
                return NotFound();
            }
            return View(diaryEntries);
        }

        // POST: DiaryEntries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EntryName,EntryDate,EntryContext")] DiaryEntries diaryEntries)
        {
            if (id != diaryEntries.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(diaryEntries);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiaryEntriesExists(diaryEntries.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(diaryEntries);
        }

        // GET: DiaryEntries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DiaryEntries == null)
            {
                return NotFound();
            }

            var diaryEntries = await _context.DiaryEntries
                .FirstOrDefaultAsync(m => m.Id == id);
            if (diaryEntries == null)
            {
                return NotFound();
            }

            return View(diaryEntries);
        }

        // POST: DiaryEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DiaryEntries == null)
            {
                return Problem("Entity set 'ApplicationDbContext.DiaryEntries'  is null.");
            }
            var diaryEntries = await _context.DiaryEntries.FindAsync(id);
            if (diaryEntries != null)
            {
                _context.DiaryEntries.Remove(diaryEntries);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DiaryEntriesExists(int id)
        {
            return (_context.DiaryEntries?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using ElizabethRobinsonDiaryEntries.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ElizabethRobinsonDiaryEntries.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/DiaryEntries/Create.cshtml
@model ElizabethRobinsonDiaryEntries.Models.DiaryEntries

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DiaryEntries</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EntryName" class="control-label"></label>
                <input asp-for="EntryName" class="form-control" />
                <span asp-validation-for="EntryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryContext" class="control-label"></label>
                <input asp-for="EntryContext" class="form-control" />
                <span asp-validation-for="EntryContext" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DiaryEntries/Delete.cshtml
@model ElizabethRobinsonDiaryEntries.Models.DiaryEntries

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DiaryEntries</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryContext)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryContext)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/DiaryEntries/Details.cshtml
@model ElizabethRobinsonDiaryEntries.Models.DiaryEntries

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryContext)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryContext)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/DiaryEntries/Edit.cshtml
@model ElizabethRobinsonDiaryEntries.Models.DiaryEntries

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DiaryEntries</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EntryName" class="control-label"></label>
                <input asp-for="EntryName" class="form-control" />
                <span asp-validation-for="EntryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryContext" class="control-label"></label>
                <input asp-for="EntryContext" class="form-control" />
                <span asp-validation-for="EntryContext" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DiaryEntries/Index.cshtml
@model IEnumerable<ElizabethRobinsonDiaryEntries.Models.DiaryEntries>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EntryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EntryDate)
            </th>
            <th>
                Actions
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EntryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EntryDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">View Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/DiaryEntries/ShowSearchForm.cshtml
<h4>Search for a diary entry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="searchPhrase" class="control-label"></label>
                <input name="searchPhrase" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index"><input type="submit" value="Back to List" class="btn btn-primary" /></a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is a simple app for entering and editing diary entries.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diary Entry Tracking App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ElizabethRobinsonDiaryEntries.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Diary Entry Tracking App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DiaryEntries" asp-action="Index">Diary Entries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DiaryEntries" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>